### ISSUE TITLE
Audio

### ISSUE THREAD

**Issue by soqman** [yasirkula/UnityEveryplaySaveToLocal#1]
Hello!

Thanx 4 u plugin. Its simple and usefull. I tried to save audio by mic (FaceCamSetAudioOnly) too. Have you tried to save videofile with original audio track by mic?

**Comment by yasirkula** [comment]
I haven't tried it. I'm guessing that the mic audio is missing after saving the file?

**Comment by soqman** [comment]
yes. everyplay create another one file (.m4a ) on the same directory with audio from mic. thanx 4 answer.
