### ISSUE TITLE
Audio not recording?

### ISSUE THREAD

**Issue by wilk3ns** [yasirkula/UnityEveryplaySaveToLocal#2]
Is there any known limitation about capturing screen with audio or this is specific to me?

**Comment by yasirkula** [comment]
FaceCam features are not supported. I forgot to add it to README, sorry. If you are having issues with in-game sounds, then it shouldn't happen. Please let me know in that case.

**Comment by wilk3ns** [comment]
@yasirkula  Yep in-game sounds are not recording

**Comment by yasirkula** [comment]
Is the audio playing correctly when you upload the video to Everyplay servers?

**Comment by wilk3ns** [comment]
Never tried so far. I'll try come back
